all:
  hosts:
    node1:
      ansible_host: 192.168.122.80
      ip: 192.168.122.80
      access_ip: 192.168.122.80
      ansible_become: yes
      ansible_user: ubuntu
    node2:
      ansible_host: 192.168.122.113
      ip: 192.168.122.113
      access_ip: 192.168.122.113
      ansible_become: yes
      ansible_user: ubuntu
    node3:
      ansible_host: 192.168.122.168
      ip: 192.168.122.168
      access_ip: 192.168.122.168
      ansible_become: yes
      ansible_user: ubuntu
  children:
    kube-master:
      hosts:
        node1:
        node2:
        node3:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
