- name: Create k8s webapp
  hosts: node1
  tasks:
    - name: install openshift
      pip:
        name: openshift

    - name: Create a k8s namespace
      community.kubernetes.k8s:
        name: cc
        api_version: v1
        kind: Namespace
        state: present

    - name: Create k8s deployment for backend
      community.kubernetes.k8s:
        namespace: cc
        state: present
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            name: backend-deployment
            labels:
              app: backend
          spec:
            replicas: 6
            selector:
              matchLabels:
                app: backend
            template:
              metadata:
                labels:
                  app: backend
              spec:
                containers:
                  - name: backend
                    image: mludolph/images:ccbackend
                    ports:
                      - containerPort: 80
                    readinessProbe:
                      httpGet:
                        path: /ready
                        port: 80
                      initialDelaySeconds: 3
                      periodSeconds: 3
                    livenessProbe:
                      httpGet:
                        path: /ready
                        port: 80
                      initialDelaySeconds: 3
                      periodSeconds: 3

    - name: Create k8s deployment for frontend
      community.kubernetes.k8s:
        namespace: cc
        state: present
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            name: frontend-deployment
            labels:
              app: frontend
          spec:
            replicas: 4
            selector:
              matchLabels:
                app: frontend
            template:
              metadata:
                labels:
                  app: frontend
              spec:
                containers:
                  - name: frontend
                    image: mludolph/images:ccfrontend
                    ports:
                      - containerPort: 80
                    readinessProbe:
                      httpGet:
                        path: /ready
                        port: 80
                      initialDelaySeconds: 3
                      periodSeconds: 3
                    livenessProbe:
                      httpGet:
                        path: /ready
                        port: 80
                      initialDelaySeconds: 3
                      periodSeconds: 3

    - name: Create a k8s service for the backend
      community.kubernetes.k8s:
        namespace: cc
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: cc-backend-service
          spec:
            type: ClusterIP
            selector:
              app: backend
            ports:
              - port: 80
                targetPort: 80

    - name: Create a k8s service for the backend
      community.kubernetes.k8s:
        namespace: cc
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: cc-frontend-service
          spec:
            type: NodePort
            selector:
              app: frontend
            ports:
              - port: 80
                targetPort: 80
