all:
  hosts:
    node1:
      ansible_host: 34.78.94.8
      ansible_become: yes
      ansible_user: alex
    node2:
      ansible_host: 34.77.84.87
      ansible_become: yes
      ansible_user: alex
    node3:
      ansible_host: 34.78.225.237
      ansible_become: yes
      ansible_user: alex
  children:
    kube-master:
      hosts:
        node1:
        node2:
        node3:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
